### ISSUE TITLE
'Wrong number of arguments' error occurs on a fresh install of checksum-tools

### ISSUE THREAD

**Issue by oceanofsound** [sul-dlss/checksum-tools#5]
On recent installations of checksum-tools (last 6 months?), we get an 'initialize': wrong number of arguments error. Nathan was able to get around it by commenting out 

require 'progressbar'

in the code.  

DN5273g9:Desktop ncoy$ checksum-tools -a generate -e .md5
/Users/ncoy/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/checksum-tools-1.2.0/bin/checksum-tools:34:in `initialize': wrong number of arguments (given 2, expected 0) (ArgumentError)
        from /Users/ncoy/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/checksum-tools-1.2.0/bin/checksum-tools:34:in `new'
        from /Users/ncoy/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/checksum-tools-1.2.0/bin/checksum-tools:34:in `progress'
        from /Users/ncoy/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/checksum-tools-1.2.0/bin/checksum-tools:43:in `block in generate'
        from /Users/ncoy/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/checksum-tools-1.2.0/lib/checksum-tools/local.rb:56:in `block in digest_file'
        from /Users/ncoy/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/checksum-tools-1.2.0/lib/checksum-tools/local.rb:55:in `open'
        from /Users/ncoy/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/checksum-tools-1.2.0/lib/checksum-tools/local.rb:55:in `digest_file'
        from /Users/ncoy/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/checksum-tools-1.2.0/lib/checksum-tools.rb:62:in `create_digest_file'
        from /Users/ncoy/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/checksum-tools-1.2.0/lib/checksum-tools.rb:52:in `block in create_digest_files'
        from /Users/ncoy/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/checksum-tools-1.2.0/lib/checksum-tools.rb:163:in `block in process_files'
        from /Users/ncoy/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/checksum-tools-1.2.0/lib/checksum-tools.rb:162:in `each'
        from /Users/ncoy/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/checksum-tools-1.2.0/lib/checksum-tools.rb:162:in `process_files'
        from /Users/ncoy/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/checksum-tools-1.2.0/lib/checksum-tools.rb:50:in `create_digest_files'
        from /Users/ncoy/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/checksum-tools-1.2.0/bin/checksum-tools:42:in `generate'
        from /Users/ncoy/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/checksum-tools-1.2.0/bin/checksum-tools:169:in `<top (required)>'
        from /Users/ncoy/.rbenv/versions/2.4.1/bin/checksum-tools:22:in `load'
        from /Users/ncoy/.rbenv/versions/2.4.1/bin/checksum-tools:22:in `<main>'
DN5273g9:Desktop ncoy$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

**Comment by oceanofsound** [comment]
Dupe of https://github.com/sul-dlss/checksum-tools/issues/4
